name: stocks-dekho-backend
version: 0
application:
  version: 1.20 # (optional)
  language: nodejs
  ports:
  - port: 8080
    ingress: true
    ingressPath: /
endpoints:
  - path: /stocks
    method: GET
    command: node build/index.js
build:
  command: vite build
  outputDirectory: build
healthChecks:
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 5
    timeoutSeconds: 5
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 15
    timeoutSeconds: 5
