name: stocks-dekho-frontend
version: 0
application:
  version: 1.20 # (optional)
  language: javascript
  ports:
  - port: 5173
    protocol: TCP
    targetPort: 5173
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    path: /
pre-exec:
  commands:  
  - cmd: date # Print the deploy date
