name: stocks-dekho-frontend
version: 0
application:
  version: 1.20 # (optional)
  language: Nodejs
  ports:
  - port: 5173
    ingress: true
    ingressPath: /
endpoints:
  - path: /
    method: GET
    command: node build/index.js
build:
  command: vite build
  outputDirectory: build
